---
- hosts: all
  gather_facts: true
  become: yes
  # become_user: root
  # become_method: su
  vars_files:
  - passwords.yml
  roles:
  - role: auto-deploy-node-app
    vars:
      repo_url: git@github.com:KnightShade391/Simple-Node-App.git